name: Behave Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  behave-tests:
    runs-on: ubuntu-latest  # Use Linux OS

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave

      # Step 4: Run Behave tests from the features folder
      - name: Run Behave Tests
        run: |
          behave features/ --junit --junit-directory=behave-results  # Specify the features folder and save results

      # Step 5: Upload Behave test results (Optional)
      - name: Upload Behave Test Results
        uses: actions/upload-artifact@v3
        with:
          name: behave-test-results
          path: behave-results/
          
      # Step 6: Annotate Test Failures
      - name: Annotate test failures
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('test-results.txt', 'utf8');
            core.setFailed(`Test Failures Detected:\n${results}`);

