name: CI (Behave) Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  behave-tests:
    runs-on: ubuntu-latest  # Use Linux OS

    permissions:
      issues: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4  #v3
      - name: print content of repo
        run: |
          ls

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave

      # Step 4: Run Behave tests from the features folder
      - name: Run Behave Tests
        run: |
          mkdir -p test-results  # Ensure the directory exists
          behave features/ --junit --junit-directory=test-results # Specify the features folder and save results
          ls test-results/
        # behave features/ --junit --junit-directory=test-results  --no-capture --no-skipped --verbose

      # Step 5: Upload Behave test results
      - name: Upload Behave Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-results
          path: test-results/
    
      # Step 6a: Create Issue
      - name: Create an issue
        if: failure()
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: |
            [${{ github.workflow }}] failed during [${{ github.event_name }}]
          assignees: ${{ github.actor }},${{ github.triggering_actor }}
          body: Bug in Program
          
      # Step 6b: Annotate Test Failures
      - name: Annotate Test Failures
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const resultsPath = path.join('test-results', 'TESTS-calculator.xml');
            const results = fs.readFileSync(resultsPath, 'utf8');
            core.setFailed(`Test Failures Detected:\n${results}`);
